workflows:
  android-workflow:
    name: Reminda Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties and environment
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          touch .env
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run Flutter Analyzer & Tests
        script: |
          flutter test
      - name: Build Android Release APK
        script: |
          flutter build apk --release --no-tree-shake-icons
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - alfiepolacas23@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: Reminda iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up environment
        script: |
          touch .env
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Run Flutter Analyzer & Tests
        script: |
          flutter test
      - name: Build iOS Application Payload
        script: |
          flutter build ios --release --no-codesign
      - name: Package iOS Release IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Reminda.ipa Payload
          mkdir -p "$CM_BUILD_DIR/build/ios/ipa"
          cp Reminda.ipa "$CM_BUILD_DIR/build/ios/ipa/"
          cd "$CM_BUILD_DIR"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/Reminda.ipa
    publishing:
      email:
        recipients:
          - alfiepolacas23@gmail.com
        notify:
          success: true
          failure: true
