// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEF5ewgZv2mg13yK5chONhy7owGkC40Q',
    appId: '1:625588239560:web:a6409b21057cda1cf679fd',
    messagingSenderId: '625588239560',
    projectId: 'schedly-b4b8d',
    authDomain: 'schedly-b4b8d.firebaseapp.com',
    storageBucket: 'schedly-b4b8d.firebasestorage.app',
    measurementId: 'G-CBKMZVRNJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQrOZBnRO6WRNygY3nCpZGl_qg2IeSqA',
    appId: '1:625588239560:android:71c8f503c86b1644f679fd',
    messagingSenderId: '625588239560',
    projectId: 'schedly-b4b8d',
    storageBucket: 'schedly-b4b8d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQrOZBnRO6WRNygY3nCpZGl_qg2IeSqA',
    appId: '1:625588239560:android:71c8f503c86b1644f679fd',
    messagingSenderId: '625588239560',
    projectId: 'schedly-b4b8d',
    storageBucket: 'schedly-b4b8d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQrOZBnRO6WRNygY3nCpZGl_qg2IeSqA',
    appId: '1:625588239560:android:71c8f503c86b1644f679fd',
    messagingSenderId: '625588239560',
    projectId: 'schedly-b4b8d',
    storageBucket: 'schedly-b4b8d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqEF5ewgZv2mg13yK5chONhy7owGkC40Q',
    appId: '1:625588239560:web:89a2789e3c67d13bf679fd',
    messagingSenderId: '625588239560',
    projectId: 'schedly-b4b8d',
    authDomain: 'schedly-b4b8d.firebaseapp.com',
    storageBucket: 'schedly-b4b8d.firebasestorage.app',
    measurementId: 'G-4GVFVMXHSW',
  );
}
